#from openai_gazebo.cube_single_disk_env import CubeSingleDiskEnv
#from openai_gazebo.moving_cube.one_disk_walk import MovingCubeOneDiskWalkEnv
from openai_ros.mycartpole_env_v1 import CartPoleEnv
from openai_ros.cartpole_stay_up.stay_up import CartPoleStayUpEnv